apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowler.fullname" . }}-ui
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/component: ui
